### ISSUE TITLE
Passing only one allocation callback configuration for each API item

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#57] opened 2016-02-22 14:05 UTC
I find that [information like the following](https://www.khronos.org/registry/vulkan/specs/1.0/apispec.html#vkDestroyInstance "Destruction of instances") will need further considerations.

```
…
If VkAllocationCallbacks were provided when instance was created,
a compatible set of callbacks must be provided here.
…
```

I guess that my knowledge is insufficient here to express exact compatibility requirements safely for the involved interfaces. But I imagine that something can be achieved in this direction if a specific software design will ensure that the same allocation callback configuration would be passed to the initialisation and finalisation function of the affected API item.
I suggest to consider the introduction of the following function pattern where another callback function will be passed for the desired work execution.

```C
…
typedef
VkResult
(VKAPI_PTR* vkWorkOnItem)(VkItem* Item);
typedef
VkResult
(VKAPI_PTR* vkWorkOnItemWithUserData)
(VkItem* Item,
 void* UserData);

VkResult
vkPerformWorkItem(vkWorkOnItem WorkCallback,
                  VkAllocationCallbacks const* Allocator);
VkResult
vkPerformWorkItemWithUserData(vkWorkOnItemWithUserData WorkCallback,
                              VkAllocationCallbacks* Allocator);
…
```

**Comment by NicolBolas** [comment] 2016-02-23 19:30
> I guess that my knowledge is insufficient here to express exact compatibility requirements safely for the involved interfaces.

The specification is very clear about this:

> Two `VkAllocationCallbacks` structures are compatible if memory created with
`pfnAllocation` or `pfnReallocation` in each can be freed with `pfnReallocation` or `pfnFree` in the other.

> But I imagine that something can be achieved in this direction if a specific software design will ensure that the same allocation callback configuration would be passed to the initialisation and finalisation function of the affected API item.

Which would require users to dramatically rearchitect their code just to perform basic usage of the API.

Not only that, that is a terrible coding style for Vulkan. It doesn't fit with the general structure of the applications that use Vulkan, as it makes the scope of an object _hard coded_ into the software itself. Not even C++ RAII is so rigid, since you can at least (in C++11) move such objects to different scopes, and such objects can be heap-allocated and managed by smart pointers. That's not possible here.

Oh, and I highly doubt the Khronos Group is going to radically re-adjust the fundamental structure of their API for something so trivial.

**Comment by elfring** [comment] 2016-02-23 19:57
I see a risk because of the provided configuration interface that software developers can pass incompatible memory management callback implementations for the Vulkan application programming interface, can't they?
So I tried to show a possibility for a few function wrappers that can take care of appropriate API calls to some degree.


>Which would require users to dramatically rearchitect their code just to perform basic usage of the API.

The users can choose in which ways they would like to extend [the usage of callback functions](https://en.wikipedia.org/wiki/Callback_%28computer_programming%29 "Programming with callback functions").
Would you like to pick such ideas up around extensions for more convenient and eventually safer software development?

**Comment by NicolBolas** [comment] 2016-02-24 14:59
> The users can choose in which ways they would like to extend the usage of callback functions.

Thank you, I know what a callback is and how they work.

> Would you like to pick such ideas up around extensions for more convenient and eventually safer software development?

Vulkan is not safe. Vulkan is not safe *by design*. C isn't safe either; neither is C++. They're all supposed to be unsafe.

And if you are so concerned about the safety of allocation callbacks, there's a much easier way to deal with it. Simply have the object that uses them hold onto the structure the user provides for its entire lifetime. Which means the user needs to make sure that any objects associated with those allocators are still around when the object is.

This would give you the same safety as your design, only _without_ forcing users into callback nonsense.

Note: I'm _not_ suggesting that this be done. Vulkan is unsafe, and I'm fine with allocation callbacks as they are. I'm just saying that if this were a problem worth solving, there are better ways to do so.

**Comment by elfring** [comment] 2016-02-24 15:12
>Vulkan is not safe by design. C isn't safe either; neither is C++.

I hope that it is possible to reduce the available software weaknesses by advanced application of these programming languages.

**Comment by TobiasHector** [comment] 2016-02-24 15:23
I agree with @NicolBolas - any discussion of adding "safer" software features to Vulkan is an automatic wontfix, because the API is unsafe deliberately as it is a high-performance API, not a safe API - to the point that adding safer features would cause performance degradation. Users of the API are expected to use the API safely and make their own guarantees as Vulkan itself makes very few.

A nice project might be to develop a safe library that is layered on top of Vulkan, which can do error checks and validation in real-time - but that project is not Vulkan itself.

**Closed by TobiasHector** 2016-02-24 15:23 UTC

**Comment by elfring** [comment] 2016-02-24 15:37
>… - to the point that adding safer features would cause performance degradation.

I am unsure at the moment on how much the run time behaviour would be influenced by the proposed small function wrappers (when they might be useful occasionally).


>A nice project might be to develop a safe library that is layered on top of Vulkan, which can do error checks and validation in real-time - but that project is not Vulkan itself.

How good is [the software "Core Validation Layers"](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers#vulkan-ecosystem-components "Vulkan Ecosystem Components") for this purpose already?

**Comment by TobiasHector** [comment] 2016-02-24 15:46
> How good is the software "Core Validation Layers" for this purpose already?
The core validation layers aren't meant to be run in real time.

> I am unsure at the moment on how much the run time behaviour would be influenced by the proposed small function wrappers (when they might be useful occasionally).
We could spend hours discussing the ins and outs of this, but I'm not sure it would really help anyone. If you can already implement this as wrappers on top of Vulkan, then you should do that in a separate project and maybe people will find it useful.
