### ISSUE TITLE
Concurrent usage of image subresources used as attachments

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#299] opened 2016-07-26 00:55 UTC
(Forked from #298.)

https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkFramebufferCreateInfo says:

> Image subresources used as attachments must not be used via any non-attachment usage for the duration of a render pass instance.

What does "duration of a render pass instance" mean? and what does "used" mean?

The glossary defines "duration" in a way that doesn't apply here ("the interval between calling the command and its return to the caller"), and I don't see a particularly obvious interpretation.

I think it could be read as:

1) The subresource must not be read/written by any command or image layout transition that are recorded in the command buffer between `vkCmdBeginRenderPass` and `vkCmdEndRenderPass`. But there's nothing stopping you using the subresource in some command recorded outside the render pass without any execution dependencies to enforce an order, or using it concurrently in another queue, as long as you only access a non-overlapping range of pixels (which implies not doing any layout transitions) so that you don't break the normal rules for read-after-write/write-after-write hazards. Or:

2) There must be an appropriate memory dependency between the render pass instance and any other read/write of the subresource. (Specifically I think the other use must happen-before an explicit `VkSubpassDependency` with `dstStageMask=COLOR_ATTACHMENT_OUTPUT`, `dstAccessMask=COLOR_ATTACHMENT_WRITE|READ`, `srcSubpass=VK_SUBPASS_EXTERNAL`, and `dstSubpass=` the first subpass that uses the attachment; or happen-after the corresponding end-of-render-pass dependency; or something a bit like that.) (And possibly the dependency should be required for any other read/write of any bytes that overlap the subresource, to include cases where e.g. the attachment is host-accessible and you access it through an aliased buffer, not just cases where you're accessing the subresource directly.)

It sounds like the intention is partly to avoid issues with compressed framebuffers, where writing to one pixel in a compressed attachment may cause nearby pixels (maybe an 8x8 tile or even larger) to appear corrupted until the attachment writes have been fully flushed, so you really shouldn't access any pixels in the subresource (even ones not being directly rendered to) without plenty of memory dependencies, which points at interpretation 2. Either way, I think the spec needs to be clearer about what it really means.

**Comment by NicolBolas** [comment] 2016-07-26 15:33
> What does "duration of a render pass instance" mean? and what does "used" mean?

Both of those are spelled out pretty clearly.

The duration of the render pass instance is exactly that: the period between the queue's execution of `vkCmdBeginRenderPass` and `vkCmdEndRenderPass`. The former starts the renderpass instance; the latter ends it. A "duration" is the period of time between a start point and end point.

The sentence says very clearly that, while a renderpass instance is active, any images which are attached cannot be used for non-attachment purposes. This seems clear enough that I don't see a need for the wording to be changed.

> But there's nothing stopping you using the subresource in some command recorded outside the render pass without any execution dependencies to enforce an order, or using it concurrently in another queue, as long as you only access a non-overlapping range of pixels (which implies not doing any layout transitions) so that you don't break the normal rules for read-after-write/write-after-write hazards. 

Yes, there is something stopping you: the very sentence you quoted. That is in fact *the whole point* of that sentence. To say that, once you start using an image as an attachment, you cannot use the image *at all*, not just some parts of it, but *at all*, until it stops being used as an attachment.

> It sounds like the intention is partly to avoid issues with compressed framebuffers, where writing to one pixel in a compressed attachment may cause nearby pixels (maybe an 8x8 tile or even larger) to appear corrupted until the attachment writes have been fully flushed, so you really shouldn't access any pixels in the subresource (even ones not being directly rendered to) without plenty of memory dependencies, which points at interpretation 2.

The best way to understand the design of pretty much anything in Vulkan's renderpass architecture is to think about what is best for tile-based hardware. This restriction is not about compression; layouts take care of that (in your case, a layout transition would be needed to access an image simultaneously for reading and writing). This restriction is about allowing TBRs to have a local copy of that data in unaccessible memory. A local copy which will only be written back out to the image's actual memory at the very end of the renderpass.

By making it expressly illegal to concurrently use any image attached to a renderpass, Vulkan allows TBRs to keep as much data as possible within a tile.

**Comment by philiptaylor** [comment] 2016-07-26 17:02
> The duration of the render pass instance is exactly that: the period between the queue's execution of `vkCmdBeginRenderPass` and `vkCmdEndRenderPass`.

I don't think that's defining what it actually means, it's just restating it in terms of "between" and "queue's execution" and "time" which aren't defined either. The whole point of synchronisation is that there isn't a single well-defined order for things - there's the order commands are called by the application, API order, execution dependency order, the order the hardware chooses to run things in, etc, and most of those are partial orders which don't really have a concept of 'between'. Anything talking about synchronisation needs to be clear what order it means.

> This restriction is not about compression

Assume the image is in `VK_IMAGE_LAYOUT_GENERAL`, with `usage=COLOR_ATTACHMENT|INPUT_ATTACHMENT`, and is used as a colour attachment in one queue and as an input attachment in another queue, so no layout transitions are needed. There's no aliasing, and each queue accesses a non-overlapping `renderArea`.

I think tile buffers don't impose the strictest requirements here. If the image is not compressed, and I write to pixel (0,0) in the first queue, and don't have any memory dependencies so the write may remain in the tile buffer / ROP cache / etc or may get flushed to memory, and concurrently I read pixel (1,0) from the second queue, the read will return identical results whether it happens before or after the flush. So read-after-nearby-write hazards shouldn't require memory dependencies here, the results should be well-defined without them. (Write-after-nearby-write hazards still do need dependencies, else the second write might get clobbered when the tile containing the first write is flushed.)

But if the image is compressed, and I write to pixel (0,0), that might update the ROP cache / etc and also recompute the compression metadata for an 8x8 tile in some hidden compression tag memory. If the second queue tries to read pixel (1,0), it might see the updated metadata before the ROP cache has been flushed, so it will decompress inconsistent data and end up with garbage. That case means we need memory dependencies for read-after-nearby-write hazards too, so it motivates the stronger requirements here.

(I assume it's okay for an implementation to use compression for an image in `GENERAL` layout when the `usage` flags restrict it to attachment usages; that seems a sensible optimisation for them to apply when they can.)

**Comment by NicolBolas** [comment] 2016-07-26 19:43
I realize that the reason I took my interpretation of that statement as I did is because of how the specification usually states these sorts of things. Allow me to explain.

It is possible to interpret that statement in 2 ways: 1) you can't use the image locally within the render pass instance in that CB (and therefore in any secondary CBs you may execute in the RPI). 2) You can't use it globally anywhere during the execution of that render pass instance.

The reason I assume that interpretation 2 is right is because nowhere else in the standard do they use the phrase "duration of a render pass instance." Anytime they refer to whether something is legal based on whether an RPI is active, the phrase is "within a render pass instance". And this is very consistent throughout the spec. Because they used a different phrase, I assumed they meant a different interpretation, with "duration" meaning execution duration.

So it's possible that they meant interpretation 1 and just used an inconsistent phrasing. So I agree that some clarification is needed.

If they mean item 1, the phrasing should be the standard one:

> Image subresources used as attachments must not be used via any non-attachment usage within a render pass instance.

If they mean item 2, the phrasing should probably be:

> Image subresources used as attachments must not be used on any queue via any non-attachment usage while the render pass instance is executing on any queue.

This would force you to use an explicit execution dependency if you want to use it as an input attachment, at any point, regardless of memory overlap.

> (I assume it's okay for an implementation to use compression for an image in GENERAL layout when the usage flags restrict it to attachment usages; that seems a sensible optimisation for them to apply when they can.)

And yet, you've given a very example of why it _wouldn't_ be OK to do so ;)

If a TBR uses compression, then using an image as an input attachment would *have to* decompress it. And for non-TBRs, input attachments are just syntactic sugar for a texture fetch. So it would only be able to use compression if it could texture fetch from a compressed format. That's somewhat unlikely.

Also, why is it so important to be able to read from a different region of an image being written? This is Vulkan, not OpenGL. You can control memory allocation explicitly; you don't have to allocate a bigger image than you want to use just to avoid multiple allocations. Just put both `VkImage`s in the same memory allocation.

**Comment by philiptaylor** [comment] 2016-07-26 20:40
> If a TBR uses compression, then using an image as an input attachment would have to decompress it. And for non-TBRs, input attachments are just syntactic sugar for a texture fetch. So it would only be able to use compression if it could texture fetch from a compressed format. That's somewhat unlikely.

TBR would decompress on-the-fly when reading back into the tile buffer, the data in memory would remain compressed. [NVIDIA says](http://international.download.nvidia.com/geforce-com/international/pdfs/GeForce_GTX_980_Whitepaper_FINAL.PDF) "The bandwidth savings from this compression is realized a second time when clients such as the Texture Unit later read the data", which I believe is saying it can texture fetch from a framebuffer-compressed image. So it's not just theoretical - the attachments really can be kept compressed in memory, as long as the spec is strict enough about memory dependencies between uses of the attachment.

> Also, why is it so important to be able to read from a different region of an image being written?

It's not, it's just important that the spec is clear enough that someone could correctly implement a validation layer for its rules, and that the validation agrees with how driver developers interpret the rules, which means all the weird edge cases need to be defined properly.

**Comment by TobiasHector** [comment] 2016-11-23 10:21
Ah I meant to respond on this to clarify - we discussed this in the WG and agreed that option **2** is the intended behaviour - which actually I read as a superset of **1**. In other words, you can't access images as anything other than an attachment if it's used as an attachment within a renderpass, either in that recording or outside it. 

The precise reasoning is actually different for different implementations - but for **2**, it basically boils down to the fact that no matter what architecture you're on, sub passes access the memory of their attachments in some fashion, and the only way to guarantee *when* that happens is with execution and memory dependencies. If you tried to access those images in any other way at the same time as the render pass, you get a pure and simple data race.

The next spec update will include the sync chapter rewrite which partially clarifies this, though the group is also working on more targeted fixes for this.

**Comment by oddhack** [comment] 2016-11-26 10:50
This should be partly addressed in the 1.0.35 spec update, as part of the synchronization language rewrite.

**Comment by oddhack** [comment] 2017-10-28 09:33
This should be done in the 1.0.65 spec update.

**Closed by oddhack** 2017-10-28 09:33 UTC
Labels: Resolving Inside Khronos, Specification
