### ISSUE TITLE
Typos: Chapters 14-35 of the KHR-only build of specification

### ISSUE THREAD

**Issue by naiveforce** [KhronosGroup/Vulkan-Docs#1483] opened 2021-03-26 11:23 UTC
[vkspec_14_35.pdf](https://github.com/KhronosGroup/Vulkan-Docs/files/6211400/vkspec_14_35.pdf)

**Comment by naiveforce** [comment] 2021-03-26 13:30
Commented pages only against spec version 170.
[vkspec_14_35_comms.pdf](https://github.com/KhronosGroup/Vulkan-Docs/files/6212065/vkspec_14_35_comms.pdf)

**Comment by oddhack** [comment] 2021-04-15 09:38
On p. 754 of the comments, you noted "This should be specified in "Valid
Usage" for the automatically-generated VU:

> pAccelerationStructures must: be a valid pointer to an array of accelerationStructureCount valid or VK_NULL_HANDLE VkAccelerationStructureKHR handles

I'm not following the meaning of the comment - the VU is generated based on
annotations in vk.xml. Why do you think
it should move to the explicit VU section?

**Comment by naiveforce** [comment] 2021-04-15 11:13
It seems that the comment got broken up while being exported into the summary version. What I've meant was that pAccelerationStructures can only be equal to VK_NULL_HANDLE if there is a nullDescriptor feature enabled, which in turn is not a general or "implicit" valid usage statement.

**Comment by oddhack** [comment] 2021-04-15 11:49
> It seems that the comment got broken up while being exported into the summary version. What I've meant was that pAccelerationStructures can only be equal to VK_NULL_HANDLE if there is a nullDescriptor feature enabled, which in turn is not a general or "implicit" valid usage statement.

@dgkoch can you speak to this? If the VU needs to be moved and qualified, that's beyond the scope of the typo fixes I'm rolling up internally.

**Comment by oddhack** [comment] 2021-04-17 09:05
On p. 973, you highlight 'imageExtent.{height,depth}' in VUIDs 00198 and 00200, but there are no comments, and it's not obvious what the issue is?

**Comment by naiveforce** [comment] 2021-04-17 09:21
All other occurrences of these structure members are formatted as "hyper links". The ones that you mention are formatted as "plain text".

**Comment by oddhack** [comment] 2021-04-19 07:39
Much of this has been addressed in the 1.2.176 spec update. Some points that were a bit more complicated than I have scope to resolve myself have been raised as separate internal tracker issues. If it's OK with you I'd like to close this now and roll out the point issues as they get resolved.

**Closed** 2021-04-19 08:06 UTC
Labels: Markup/Editing

**Comment by oddhack** [comment] 2021-05-17 08:07
> > It seems that the comment got broken up while being exported into the summary version. What I've meant was that pAccelerationStructures can only be equal to VK_NULL_HANDLE if there is a nullDescriptor feature enabled, which in turn is not a general or "implicit" valid usage statement.
> 
> @dgkoch can you speak to this? If the VU needs to be moved and qualified, that's beyond the scope of the typo fixes I'm rolling up internally.

The Ray Tracing TSG discussed this internally and concluded "agreed it maybe parses a bit awkwardly, but it's definitely not the only place in the spec where you need to read multiple VUs together to figure out what is valid. Closing as will not fix."
