### ISSUE TITLE
Some global constants not required by any feature or extension

### ISSUE THREAD

**Issue by keidax** [KhronosGroup/Vulkan-Docs#1511] opened 2021-04-21 03:31 UTC
I'm working to generate some bindings from `vk.xml`, and noticed a strange discrepancy. Most of the constants from the "API Constants" section are listed in a `require` section for an extension or feature. However, these six are not:
```
VK_MAX_PHYSICAL_DEVICE_NAME_SIZE
VK_UUID_SIZE
VK_MAX_EXTENSION_NAME_SIZE
VK_MAX_DESCRIPTION_SIZE
VK_MAX_MEMORY_TYPES
VK_MAX_MEMORY_HEAPS
```

For consistency, could these be included in the `VK_VERSION_1_0` feature alongside the other constants?

**Comment by oddhack** [comment] 2021-04-21 07:42
If you want to propose an MR to that effect we'd probably accept it. Harmless so long as they appear in the right feature block.

However, traversal of the XML must be done in dependency order starting with the extension or feature top-level APIs. All of these enums are used as array sizes in structure members, and will be pulled in as dependencies of that structure at that point. So there is no need for it in terms of the schema.

**Comment by keidax** [comment] 2021-04-22 02:21
Okay, thanks. After looking through a few other issues and reading `reg.py`, I think I understand how the dependencies are pulled in. If anyone else finds this, the relevant code starts at https://github.com/KhronosGroup/Vulkan-Docs/blob/67f599afee77b0e598e7a325f13b9878edcacdfd/scripts/reg.py#L655

I guess it might be best to keep the schema as-is. It functions as a heads-up to anyone else trying to parse the XML that they'll want to recursively load dependencies.

**Comment by oddhack** [comment] 2021-05-04 05:42
Closing as it appears the issue is resolved for you.

**Closed by oddhack** 2021-05-04 05:42 UTC
