### ISSUE TITLE
queue priority

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-Docs#1589] opened 2021-07-23 10:19 UTC
How to create multiple queues from the same family, but with different global priorities? For example, one compute queue with low priority and one compute queue with normal?

**Comment by r-potter** [comment] 2021-07-23 10:38
Duplicate of https://github.com/KhronosGroup/Vulkan-Docs/issues/1398?

**Comment by konstantinegorov** [comment] 2021-07-23 13:04
Oh, I'm sorry. Yes, it is a duplicate

**Closed** 2021-07-23 13:06 UTC
