### ISSUE TITLE
Man page documentation error.

### ISSUE THREAD

**Issue by splodginald** [KhronosGroup/Vulkan-Docs#53] opened 2016-02-22 00:34 UTC
Searching on google for "VkLayerProperties", the first hit is:
https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkEnumerateDeviceLayerProperties.html

Which gives documentation for the vkEnumerateDeviceLayerProperties function.

All links to VkLayerProperies in the Description section are 404.

**Comment by NicolBolas** [comment] 2016-02-22 02:31
Duplicate of #44.

**Comment by oddhack** [comment] 2016-02-22 06:33
Improvements to the ref pages are underway, will update #44 when they hit.

**Closed by oddhack** 2016-02-22 06:33 UTC
Labels: duplicate
