### ISSUE TITLE
Ref page stubs need to be filled in with actual content

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#44] opened 2016-02-21 20:20 UTC
Vulkan as an API depends as much on struct documentation as it does function and enumerator docs. Every API function which has a unique `Info` struct for it does have documentation for that struct in its own documentation page. However, structs that are not bound to a particular function don't seem to be present.

For example, `VkPipelineShaderStageCreateInfo`. This data structure is used by several functions. And `vkCreateRenderingPipelines` does try to link to the definition of this struct. But it isn't anywhere, either in the individual files or the amalgam HTML document. This is a pretty big hole in the reference docs, and that struct is far from the only one.

**Comment by ratchetfreak** [comment] 2016-02-21 20:27
dupe of #18

**Comment by NicolBolas** [comment] 2016-02-22 02:14
@ratchetfreak  That's not really a duplicate. That bug is about a specific structure in a specific extension. This bug is about the entire documentation.

**Comment by oddhack** [comment] 2016-02-22 06:17
The author is working on some more updates which hopefully will get pushed soon, though I can't speak for their schedule, or whether that will complete coverage. Once they get signed up to the github team I'll assign it over to them.

**Comment by oddhack** [comment] 2016-02-22 22:54
Reassign to the ref page author for followup.

**Comment by SaschaWillems** [comment] 2016-03-17 08:56
Is there any ETA on this? For e.g. [vkCreateGraphicsPipelines](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCreateGraphicsPipelines.html) all the links under the Create Info Details lead to 404s (mostly create info structures) which is rather inconvenient, especially if people try to get into Vulkan and are presented with 404s on such important infors.

**Comment by oddhack** [comment] 2016-03-17 10:33
I believe Graham is at GDC; hopefully he'll post with an update on his plans. The best I could do in the shorter term is fill out the 404s with near-empty "TBD" pages containing the struct definitions and not much else. We're pretty focused on trying to keep up with public feedback on the spec and the ref pages are a lower priority, TBH.

**Comment by oddhack** [comment] 2016-03-26 02:00
I created a bunch of stub pages which just serve to replace 404s with something indicating that the page needs content. They will hopefully get filled in over time.

**Comment by oddhack** [comment] 2016-07-11 02:44
The ref page documentation is now extracted directly from the spec source, or autogenerated if it isn't in the spec at all. It is in a considerably better state. Everything in the API should be documented at this point and the documentation will (obviously) stay consistent with the spec.

That's not to say it's perfect. The ref pages don't read quite like traditional man pages now, and there are gradual improvements that can be made. Also the single-page PDF ref page document build is currently broken for arcane asciidoc reasons I haven't fully figure out yet, and the equations sometimes aren't coming through to the generated HTML properly. But those will get fixed soon and I'm going to close this. Feel free to raise specific issues about specific pages.

**Closed by oddhack** 2016-07-11 02:44 UTC
Labels: Ecosystem (Ref Pages)
