### ISSUE TITLE
Who at Khronos did coke when wrote 6.6.1?

### ISSUE THREAD

**Issue by procedural** [KhronosGroup/Vulkan-Docs#775] opened 2018-08-26 14:48 UTC
The self-dependency part is nonsensical!

**Comment by procedural** [comment] 2018-08-26 17:50
w3 people questioned them too a year ago:

https://lists.w3.org/Archives/Public/public-gpu/2017Sep/0015.html

> CW: to close this topic: we don’t put memory barriers inside subpasses. If you need this for your use case you do a different subpass.

> JG: I am curious why this wound up in the Vulkan spec…

**Comment by jeffbolznv** [comment] 2018-08-27 16:17
I reviewed this section and it is mostly just a list of restrictions on how barriers are used within a renderpass. Most of these restrictions derive from the needs of tilers, not wanting to have to flush in the middle of a subpass due to a "bad" barrier.

Do you have any specific questions or can we close this?

**Comment by procedural** [comment] 2018-08-27 19:10
I have 2 specific questions:

Why self-dependency? Why not, I don't know, a flag on a pass that tells 'I want to use barriers in this subpass'?

Why specify self-dependency *multiple times*?

> More than one self-dependency can be declared for each subpass.

What the hell was going on in the head of a person who wrote this?

Whyyy?

**Comment by procedural** [comment] 2018-08-27 19:39
@jeffbolznv can someone visualize this? I think in pictures, not words, usually the word 'self-dependency' in DFGs means a loop where a node executes itself multiple times until a condition break, it looks like Vulkan uses other definition of a word 'self-dependency'.

Can a picture be drawn? At least in paint, or anything?

**Comment by jeffbolznv** [comment] 2018-08-27 19:46
The render pass is a graph where nodes are subpasses and edges are dependencies. A self-dependency is a dependency from a subpass to itself which is defined to mean that the subpass may have a pipelinebarrier inside it when the subpass is recorded.

So from the graph point of view, it is indeed a loop from a node to itself. But it's not interpreted to mean that the subpass is "executed" multiple times, just that it has pipelinebarriers in it.

**Comment by procedural** [comment] 2018-08-27 19:51
Say a person specified multiple self-dependencies for multiple barriers within a subpass. How an implementation will distinguish which self-dependency related to which barrier?

**Comment by jeffbolznv** [comment] 2018-08-27 19:55
Each barrier recorded during the subpass just needs to be a subset of one of the self-dependencies. Doesn't matter which one, and one could be "used" multiple times. The self-dependencies just let the driver "prepare" for types of barriers that would require the tiler to flush (e.g. reserving memory to flush to).

**Comment by procedural** [comment] 2018-08-27 19:56
> The self-dependencies just let the driver "prepare" for types of barriers that would require the tiler to flush (e.g. reserving memory to flush to).

I see. Can someone add this and other such simple to understand explanations to 6.6.1?

**Comment by procedural** [comment] 2018-08-27 20:10
[One of the Intel engineers finds the language of 6.6.1 overly complicated too](https://twitter.com/notCamelCase/status/1019322862212173824), would've been MUCH simpler if it just listed things you can and can not do with self-dependencies and subpass barriers, preferably written in simple English.

**Comment by krOoze** [comment] 2018-08-27 20:49
@procedural one better: the chapter can be mostly deleted, because it is mostly duplicate of existing VUs

**Comment by procedural** [comment] 2018-08-28 02:53
@krOoze you are part of a problem then.

**Comment by procedural** [comment] 2018-08-28 03:01
w3 people could not figure out the meaning of 6.6.1 a year ago too: https://lists.w3.org/Archives/Public/public-gpu/2017Sep/0015.html

> JG: Vulkan spec section 6.6.1 about dependencies

> CW: think this too hard and niche, and we shouldn’t put it in.

**Comment by krOoze** [comment] 2018-08-28 11:15
> part of a problem

's my middle name. #756

Maybe make a PR. You can always wordsmith something a bit better. I don't see the big problem though.

**Comment by oddhack** [comment] 2018-09-10 15:29
We discuss this today, and agree that you should propose a PR if you want to improve the language here.

**Closed by oddhack** 2018-09-10 15:29 UTC

**Comment by procedural** [comment] 2018-09-12 16:12
Suggesting I should propose a PR assumes that I know what that person meant when he wrote 6.6.1.

**Comment by krOoze** [comment] 2018-09-12 18:01
Suggesting someone else should do something about it assumes he knows what actionable issues you have with the current wording.

What you have provided so far is largely mining the web for people feeding your confirmation bias.

Try to articulate what you do not understand about the subject like the proper engineer you are.
Or try to state your current understanding of the feature. The mistakes you make doing so would be equally useful to pinpoint the problems.

<hr />

So, I proposed #756, which makes sure related VU is at least correct. It is a horrible sentence (which can't be helped much), but your issue about dependency&ndash;barrier matching seems clear to me by "must have been created with at least one" (i.e. basically your usual "there exists a" quantifier).

And proposed #778 which adds stuff from the chapter as a proper VU (which means it will hopefully be validated for you by the layers eventually).

So, the chapter is practically a dump of restrictions, which are\should be VUs in the first place.
If we want to preserve the chapter at all, I guess it should be filled with some introductory paragraph(s) instead, let's say something like:

> Self-dependency feature allows using a restricted kind of pipeline barriers (`vkCmdPipelineBarrier`) inside a subpass recording. On renderpass creation time self-dependencies are defined, which defines the subset of stage and access flags that can be used in the `vkCmdPipelineBarrier` (see `vkCmdPipelineBarrier` VU section).

And the related synchronization behavior is described above in `vkCmdPipelineBarrier` descriptions. I guess it could be moved to this chapter or at least linked to.

What else?

**Comment by procedural** [comment] 2018-09-13 06:28
I just realized the issue was closed by a person with the username "oddhack". It explains every question I had.
