### ISSUE TITLE
Clarification about whether image format or image view format is relevant for blending support

### ISSUE THREAD

**Issue by gmueckl** [KhronosGroup/Vulkan-Docs#1392] opened 2020-11-12 16:46 UTC
VUID-VkGraphicsPipelineCreateInfo-blendEnable-02023 says (highlighting is mine)

> If rasterization is not disabled and the subpass uses color attachments, then for each color attachment in the subpass the blendEnable member of the corresponding element of the pAttachment member of pColorBlendState must be VK_FALSE if the **attached image’s** format features does not contain VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT

But VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT is described thus (highlighting is mine):

> VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT specifies that an **image view** can be used as a framebuffer color attachment that supports blending and as an input attachment.

These two passages are not quite consistent. One requires the image format to support blending, while the other refers to the image view format. Which one of the formats need to support blending in order to be usable for blending operations?

For reference, the validation layer tests the format properties for the image format for the presence of the feature bit and ignores the image view.

**Comment by sfricke-samsung** [comment] 2020-11-15 06:33
So I think this **should** be making use of the [potential format features](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#potential-format-features). There are some similar cases with attachments in `VkSubpassDescription` as well.

The issue is at pipeline creation time the Validation Layers don't know which `VkFramebuffer` is being used, thereby not knowing what image view format to use.

So what I think might be done is add clarification that `02023` refers to the image potential format features and then add an additional VU at `vkCmdBeginRenderPass` to then check for the image view's format feature

**Comment by sfricke-samsung** [comment] 2020-11-20 09:13
So confirmed in working group on the following course of actions (which I plan to handle)

- (Spec) Change 02023 to use "potential format features"
- (Spec) Add a VU at `vkCmdBeginRenderpass` to check for the Image View format features
- (Validation Layers) Update 02023 to use "potential format features"
- (Validation Layers) Add new VU coverage to validation layers

**Comment by gmueckl** [comment] 2020-12-14 11:19
Can you elaborate how this resolves the current issue? Specifically, I'm not clear which of the following options will be true after that change:

1. Only the image format needs to support blending.
2. Only the image view format needs to support blending.
3. Both the image and image view formats need to support blending.

Which one is it supposed to be?

**Comment by sfricke-samsung** [comment] 2020-12-14 16:05
So the old VUID `2023`  will basically become 2 new VUs

1. At pipeline creation time, the color `VkAttachmentDescription::format` must have a potential format feature of `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT`

2. At draw time, the known `VkImageView`'s format (with the tiling from the `VkImage`) there must also be `VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT`

So to answer your series of questions, `VkImage` and `VkImageView` must have the same format unless using mutable formats, but if they are different, the `VkImageView` format is what needs the support (at draw time)

**Comment by oddhack** [comment] 2021-01-19 13:52
This should be fixed in the 1.2.167 spec update.

**Closed by oddhack** 2021-01-19 13:52 UTC
Labels: Resolving Inside Khronos
