### ISSUE TITLE
PDF links do not work.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/Vulkan-Docs#462] opened 2017-02-17 16:38 UTC
I didn't report it last time since there was already a bug on HTML links, and I thought they were rooted in the same problem. But apparently not.

None of the links to functions/structures in the PDF work. All of the in-PDF links look like "#vkGetPhysicalDeviceFormatProperties". And those don't work in either of the two PDF readers I tried (SumatraPDF and Foxit Reader). I believe that these are being interpreted as HTML links as opposed to in-PDF links.

The links to specific sections work fine. Another piece of evidence that they are considered HTML links is that my PDF reader allows me to copy the link text from HTML links, but *not* to in-PDF links. I can copy links to functions/structures, but not links to sections and chapters.

I did confirm that I'm looking at the 1.0.41 PDF, downloaded just a few minutes ago from the Vulkan registry. It's the version with all of the extensions.

**Comment by TobiasHector** [comment] 2017-02-17 16:47
Strangely I saw that happen once, but then I suddenly stopped seeing it happen, and haven't been able to reproduce it since (I only use chrome to view it)

Now that at least someone else has a confirmed sighting and I know I'm not just losing my mind, I think I know how to fix it.

**Comment by oddhack** [comment] 2017-02-17 22:45
@TobiasHector AFAICT, config/vulkan-macros/extension.rb is always unconditionally injecting HTML in LinkInlineMacroBase (and other macros like Normative/Strong/Param/CodeInlineMacroBase as well). So clicking on a link in the 1.0.41 vkspec.pdf from xpdf opens a browser instance of vkspec.html. The right set of changes here might be to inject asciidoctor link markup, perhaps at an earlier processing stage if required.

**Comment by TobiasHector** [comment] 2017-02-20 09:38
Yea that was what I was going to change. I basically just need to change from "just" inserting html, to creating proper rendered inline links - which will work for all backends that support linking.

**Comment by oddhack** [comment] 2017-02-20 10:17
+1. The surprising thing is that pumping pure HTML into the PDF output doesn't just produce gibberish in the readers.

**Comment by TobiasHector** [comment] 2017-02-20 10:22
AFAICT the pdf backend understands a bunch of html tags directly, and thus "does the right thing" for external links. But since xrefs are specialised somewhat, it just tries to throw down an external link to "#<section>" which is meaningless (unless you just so happen to be viewing the pdf in a web browser - whoops).

**Comment by oddhack** [comment] 2017-02-27 07:24
This should be fixed in the 1.0.42 spec update.

**Closed by oddhack** 2017-02-27 07:24 UTC
Labels: bug, Specification
