### ISSUE TITLE
3 duplicate VUIDs with prefix VUID-VkPipelineInfoKHR

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/Vulkan-Docs#1857] opened 2022-05-18 18:50 UTC
When building validusage for 1.3-extensions, I get these warnings:

asciidoctor: WARNING: <stdin>: line 44399: id assigned to anchor already in use: VUID-VkPipelineInfoKHR-sType-sType
asciidoctor: WARNING: <stdin>: line 44400: id assigned to anchor already in use: VUID-VkPipelineInfoKHR-pNext-pNext
asciidoctor: WARNING: <stdin>: line 44401: id assigned to anchor already in use: VUID-VkPipelineInfoKHR-pipeline-parameter

This is causing build failures in my own downstream build of Vulkan-ValidationLayers.

This seems unintended, but I don't know the fix.
I think it's caused by https://github.com/KhronosGroup/Vulkan-Docs/commit/71decb7f868d3891974eab139f03c7c6c87fea4d

I noticed that chapters/pipeline_info.txt is included twice.  Once in [the body of pipeline.txt](https://github.com/KhronosGroup/Vulkan-Docs/commit/71decb7f868d3891974eab139f03c7c6c87fea4d#diff-74426418f44715bc0abb48af69c65df1d46df5e1d5cb6e2e6584475962595f07R48) and once in [VK_EXT_pipeline_properties/pipeline_properties.txt](https://github.com/KhronosGroup/Vulkan-Docs/commit/71decb7f868d3891974eab139f03c7c6c87fea4d#diff-8e16e1907a11ad36e6ee29f8d194928a62ff18b6e497965f2ccd789c36f9a9f9R40)

**Comment by dneto0** [comment] 2022-05-18 19:16
Hm.  I think my downstream build failure is something different.

**Comment by oddhack** [comment] 2022-05-19 03:20
We're aware of the issue and working it internally. You have identified the cause but restructuring the markup to avoid this is going to take a little thought. Unfortunately the validation layers work by ignoring asciidoctor conditionals (other than to track what they are), so despite the fact that the markup only gets processed once when generating an output document, it gets processed twice in this case.

Could you say more about how this is affecting the validation layers build?

**Comment by oddhack** [comment] 2022-06-02 12:37
The duplicate VUID issue should be resolved in the 1.3.216 spec update.

**Closed by oddhack** 2022-06-02 12:37 UTC
