### ISSUE TITLE
Does vkDestroySwapchainKHR unacquire all acquired images?

### ISSUE THREAD

**Issue by pc-john** [KhronosGroup/Vulkan-Docs#1893] opened 2022-07-17 17:05 UTC
Looking at the spec for vkDestroySwapchainKHR, I found:

> swapchain and all associated VkImage handles are destroyed, and must not be acquired or used any more by the application.

What does "must not be acquired" mean here? Does it mean that I must unacquire VkImage handles before destroying the swapchain? How to do that?

I was hoping that vkDestroySwapchainKHR will unacquire all its VkImages. But spec is not clear to me on this point.

**Comment by krOoze** [comment] 2022-07-17 17:25
> Does `vkDestroySwapchainKHR` unacquire all acquired images?

No, it destroys them.

> What does "must not be acquired" mean here?

It means that after destruction, it is not allowed to use the `VkImage` handles in any way.

**Comment by pc-john** [comment] 2022-07-17 17:46
> > Does vkDestroySwapchainKHR unacquire all acquired images?
> No, it destroys them.

Sorry, I do not want to be awkward, but your answer suggest that the images stays acquired and this acquired state survives the image and swapchain destruction. Theoretically, it might mean leaked resources, etc.

What I was expecting is that this acquired state is removed from them at the moment of swapchain destruction.

**Comment by krOoze** [comment] 2022-07-17 20:24
The images cease to exist. They would have no state one way or the other.

**Comment by pc-john** [comment] 2022-07-18 06:40
I am getting what you are saying. But it is not based on Vulkan spec. Vulkan spec is not clear on this point.

AFAIK, spec does not say if acquired state is associated with resources or not. And it might be unless doc explicitly specifies it is not. And surely, Vulkan doc does not say anything about the resource association as it is a driver implementation detail.

So there are two possibilities:
1. It is not associated with any resources and destroying swapchain that has many vk::Images acquired is perfectly ok. In this case we can say that acquired state is released at the moment of destroying swapchain. It is effectively no-op.
2. It is associated with resources. In that case vkDestroySwapchainKHR have to release them, or it must be forbidden to call vkDestroySwapchainKHR on swapchain with acquired images.

Look at at from the point of resource life cycle. If you acquired something, you have to release it. Even if it means no-op. But the complete lifecycle shall be specified. If you call malloc(0), somebody might claim that there is no need to call free() because you did not allocate anything. Yet, internally, some resources might be allocated. You are obliged to call free() unless null was returned from malloc.

So, if you acquired vk::Image, you shall release it using vkQueuePresentKHR or in vkDestroySwapchainKHR. Currently, it is not specified if vkDestroySwapchainKHR releases it or it shall be forbidden to call vkDestroySwapchainKHR when there are acquired vk::Images.

**Comment by krOoze** [comment] 2022-07-18 08:47
> And surely, Vulkan doc does not say anything about the resource association as it is a driver implementation detail.

Indeed. And so the Vulkan specification **does not** say anything on the matter. Why should it prohibit or mandate implementations to have implementation details?

> In this case we can say that acquired state is released at the moment of destroying swapchain.

No. We can say the Image stopped existing by destruction. Things that do not exist do not have any state except non-existence. Destruction generally does not modify state. It unmakes it.

>  If you acquired something, you have to release it.

Of course not. If you multiply an `int`, does it mean you have to divide it before destruction?

> Currently, it is not specified if vkDestroySwapchainKHR releases it or it shall be forbidden to call vkDestroySwapchainKHR when there are acquired vk::Images.

The specification does one better. It says it destroys the images. It does not say it destroys released images. It says it destroys **all** the images.

**Comment by stonesthrow** [comment] 2022-07-18 16:26
There is some detail in the spec: vkDestroySwapchain
_"The application must not destroy a swapchain until after completion of all outstanding operations
on images that were acquired from the swapchain. swapchain and all associated VkImage handles are
destroyed, and must not be acquired or used any more by the application. The memory of each
VkImage will only be freed after that image is no longer used by the presentation engine. For
example, if one image of the swapchain is being displayed in a window, the memory for that image
may not be freed until the window is destroyed, or another swapchain is created for the window.
Destroying the swapchain does not invalidate the parent VkSurfaceKHR, and a new swapchain can be
created with it."_

"Acquire" is from vkAcquireNextImage. Meaning the driver/app is has acquired write authority from the PE.
To release the Image back to the Presentation Engine you use vkQueuePresent. If you delete the Swapchain while the Images are being used by the Vulkan driver - bad things can happen. 
As stated above, when the app has released all the Images back to the PE. It can call vkDestroySwapchain, which will release the memory resources of the Images. But will do so when the PE doesn't have one or more queued for use (composition or scan out).

**Comment by pc-john** [comment] 2022-07-18 19:28
Stonesthrow, thanks!

> If you delete the Swapchain while the Images are being used by the Vulkan driver - bad things can happen.

Clearly, there must not be any rendering in progress. But "being used" - does it also include "acquired" image on which no access is being performed and all scheduled jobs were already completed?

One example: is it safe to call vkAcquireNextImage followed by vkDestroySwapchain? Typical scenario would be vkAcquireNextImage returned Suboptimal return code, which means that an image was acquired. But I might decide to destroy swapchain and create new one that would match the surface dimensions. Do I need to call vkQueuePresent before I call vkDestroySwapchain? I read spec including the place you mentioned, but did not found clear answer.

I have got an impression that Vulkan core team works on a new extension that shall clarify many things around presentation. If it is true, thanks for such job! Anyway, thanks for improving Vulkan!

**Comment by krOoze** [comment] 2022-07-18 20:23
> You yourself confirmed that we do not know whether the driver allocated something, or not. It is really up to the driver.

I don't quite understand the concern with implementation details. By definition, if you are a consumer of a public API, then you do not care about implementation details. Otherwise you could strech your argument to everything. Every action (or inaction) can theoretically result in some resource being allocated. You just don't care, because that is implementation's concern to deal with.

> Just because of success code you know that the uint32_t is now not referring to any acquired image.

And I don't care, because the specification says it destroys **all** the swapchain's images (regardless of their state).

> where is written that this is allowed operation?

What is not forbidden is allowed. I mean, sum of all allowed things is an infinite set. That is something a specification cannot contain. For example, where is it written that destroying an image containing a picture of a kitty is allowed?

> But "being used" - does it also include "acquired" image on which no access is being performed and all scheduled jobs were already completed?

No, because that would be unsatisfiable condition. That would make it impossible to ever destroy a swapchain object.

The specification is quite obvious on that point:

> All uses of presentable images acquired from swapchain **must** have completed execution

If it instead wanted to wholesale forbid all acquired images, it would just say so and would not bother to qualify further.

> One example: is it safe to call vkAcquireNextImage followed by vkDestroySwapchain?

Yes.

> I have got an impression that Vulkan core team works on a new extension that shall clarify many things around presentation. 

The main problem with Vulkan was that you have no way to know when a Semaphore you borrowed to `vkQueuePresent` is finished. I believe that was sorta addressed by the `VK_KHR_present_wait`. That though has the drawback that it still keeps unextended Vulkan in a broken state indefinitely.

<hr>

While we are here dissecting this in extreme detail, I did notice some discrepancies that when fix could help this a little:

1) 
> `swapchain` and all associated `VkImage` handles are destroyed, and **must** not be acquired or used any more by the application.

It is somewhat awkward to say the application must not acquire the images anymore, since it really has no means to do so, since the swapchain is already destroyed.

2)
It is somewhat tempting to think the images become acquired or released based on the state of the provided semaphore. But I am 98 % sure they reach these states immediatelly after the return from the command call.

If that is so, the asyncish nature of `vkAcquire` could make it tempting to thing the swapchain is acquired and "in use" until the acquire semaphore is signaled. Though I think that is not so, and spec should enforce that interpretation.

3) It feels the swapchain images should be in the externsync for `vkDestroySwapchain` in the Implicit Externally Synchronized Parameters list, but they seem missing in there.

**Comment by cubanismo** [comment] 2022-07-18 23:56
You can destroy a swapchain with acquired images. As @krOoze states, nothing prohibits it, so it is allowed.

Images are in use when Vulkan commands queued against them are incomplete. vkAcquireNextImageKHR() is not a queue operation, and is intended to wrap hardware and/or OS-specific work, represented in the spec by the presentation engine, that is outside the scope of Vulkan in general. Hence, it does not cause images to be in use from Vulkan's point of view. If there is pending presentation engine work associated with the image, that is the WSI implementation's job to manage, which might mean deferring memory destruction until it is complete, but as far as the Vulkan specification (and hence the application) is concerned, the image is destroyed and invalid as soon as the swapchain is destroyed. The note about potential deferred destruction is just to guide applications that the associated memory may not be immediately available for re-use for implementation-specific reasons. If some implementation needs to allocate internal resources for images in the acquired state, it is again the implementation's responsibility to destroy those when the image is destroyed just like any other implementation-specific resources associated with the swapchain image or its memory. If they needed to be managed separately by the application, they would be specifically exposed in the Vulkan API as an object.

Note acquire is slightly different than its inverse operation, present, which was purposely specified as a queue operation (vkQueuePresentKHR()). Presentation can involve a combination of Vulkan work and presentation engine work, and the application does need to ensure the Vulkan portion of that work is complete before destroying a swapchain, which is an area that is currently under-specified (I.e., a spec bug).

Going back to the original question, I don't know why the spec specifically states images of destroyed swapchains "must not be acquired" anymore, as there's no valid way to acquire them after destroying the swapchain. Like many things we've cleaned up over the years in the WSI language, it may be a dangling clause from an earlier iteration of the spec that no one has noticed yet, likely because it's not wrong per-se, just redundant and apparently somewhat misleading. However, you can't acquire something you already have, so I don't think it was intended to speak to the current state of the images, but rather forbid future state changes.

**Closed** 2022-07-19 07:03 UTC
