### ISSUE TITLE
Build acceleration VU contains "may"

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#1528] opened 2021-05-11 20:08 UTC
> [[VUID-{refpage}-pInfos-03767]]
    For each element of pname:pInfos, if its pname:mode member is
    ename:VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR, then for each
    sname:VkAccelerationStructureGeometryKHR structure referred to by its
    pname:pGeometries or pname:ppGeometries members, if pname:geometryType
    is ename:VK_GEOMETRY_TYPE_TRIANGLES_KHR, if its
    pname:geometry.triangles.transformData member was not NULL when
    pname:srcAccelerationStructure was last built, then it may not be NULL

May there at the end. Possibly a duplicate of `VUID-{refpage}-pInfos-03766`?

Plus bad markup for `NULL` and not sure if `NULL` is even appropriate as it looks like a `VkBuffer`. Generally it is kinda hard to read and not sure what it says.

**Comment by dgkoch** [comment] 2021-05-27 13:42
agree it should be `must:`

03767 is definitely not a duplicate of 03766.  
One says: 
If (a bunch of conditions) - and it was NULL before, it must be NULL now. 
The other says
If (a bunch of conditions) - and it was not NULL before, it must not be NULL now. 

`NULL` (or 0) is correct, since `transformData` is a VkDeviceOrHostAddressConstKHR in this case.  There is a `transformData` in the NV extension that is a VkBuffer, but that is not the one referenced here.

**Comment by oddhack** [comment] 2021-06-07 06:12
This should be fixed in the 1.2.180 spec update.

**Closed by oddhack** 2021-06-07 06:12 UTC
Labels: Ray Tracing
