### ISSUE TITLE
Secondary command buffer queue family mismatches

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#296] opened 2016-07-19 20:48 UTC
Say I create a command pool P1 with a graphics queue family, and allocate a secondary command buffer C1 from that pool. I record a render pass with a `vkCmdDraw` into C1.

Then I create a command pool P2 with a transfer-only queue family, and allocate a primary command buffer C2 from that pool. I use `vkCmdExecuteCommands` to execute C1 from C2.

Then I submit C2 to a queue from the transfer-only queue family.

Clearly this shouldn't work, since it's trying to do a `vkCmdDraw` on a transfer-only queue. But I can't see anything in the specification to forbid this case.

`vkCmdExecuteCommands` doesn't mention any restrictions on the pools or queues of its `pCommandBuffers`.

`VkSubmitInfo` only says:

> Any given element of `pCommandBuffers` must have been created on a `VkCommandPool` that was created for the same queue family that the calling command's queue belongs to 

and doesn't mention the queue families of secondary command buffers.

Am I missing something here, or is this insufficiently specified?

A slightly more subtle case is when P1 is a transfer-only queue family, and secondary buffer C1 does a transfer operation; and P2 is a graphics-and-transfer queue family, and C2 executes C1. Superficially that sounds like it could work since the transfer operation is supported on both, but in practice I guess the transfer command on the transfer-only queue might get compiled to a DMA transfer or whatever, while the graphics queue would have to implement it as a memcpy compute shader or something, so it still wouldn't make sense to execute C1 on the graphics queue. It only makes sense when their queue families are identical.

I assume it's desirable to allow primary and secondary command buffers from different pools (so you can record secondaries in separate threads with per-thread pools), so there shouldn't be any restrictions added on pool equality, just on their queue families.

Probably `vkCmdExecuteCommands` should add a requirement like:

"Any given element of `pCommandBuffers` must have been created on a `VkCommandPool` that was created for the same queue family that the `VkCommandPool` that `commandBuffer` was created on was created for."

(but preferably with less tortuous English).

**Comment by jessebarker** [comment] 2016-07-19 21:57
Your initial premise is invalid.  You cannot record a render pass into a secondary command buffer (valid usage language for vkCmdBeginRenderPass expressly requires the command buffer to be a primary).  I haven't thought all the way through the rest of your conditions to see if it is still possible to contrive the remainder of the situation in such a way as to cause a problem.

**Comment by jeffbolznv** [comment] 2016-07-19 22:05
@jessebarker, you can record Draw commands in a secondary command buffer (VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT).

**Comment by jessebarker** [comment] 2016-07-19 22:30
@jeffbolznv, sure, but the opening statement says:

Say I create a command pool P1 with a graphics queue family, and allocate a secondary command buffer C1 from that pool. I record a render pass with a vkCmdDraw into C1.

This suggests to me that the begin and end render pass are in C1 (along with any subpasses, draws, etc.), which is what I'm saying is not valid usage.  Possibly I misunderstood that statement?

**Comment by jeffbolznv** [comment] 2016-07-19 22:40
OK, I agree there is a mistake in the example, but if you take another graphics-only command that can execute outside a render pass (e.g. vkCmdClearDepthStencilImage) I think the issue is still valid.

**Comment by philiptaylor** [comment] 2016-07-19 22:42
Ah, sorry, that was a mistake. Render passes make everything complicated... Replace with e.g. `vkCmdDispatch` on a compute queue.

**Comment by jessebarker** [comment] 2016-07-19 22:53
Agreed.  I think this could be better specified.

**Comment by oddhack** [comment] 2016-08-05 12:40
This should be fixed in the 1.0.23 update.

**Closed by oddhack** 2016-08-05 12:40 UTC
Labels: Resolving Inside Khronos, Specification
