### ISSUE TITLE
`vkAcquireNextImageKHR` should specify the state of its semaphores and fences when it fails\timeouts

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#2009] opened 2022-12-13 21:33 UTC
`vkAcquireNextImageKHR` should specify the state of its semaphores and fences when it fails\timeouts.

Common sense probably says the semaphores and fence should not be touched, but it seems to be formally missing in the specification, and there is reasonable doubt the command could be polluting those privitives.

**Comment by ShabbyX** [comment] 2022-12-14 22:30
I have a fix for this in review since a couple weeks ago. Your common sense is correct, semaphore and fence would be untouched.

**Comment by ShabbyX** [comment] 2022-12-14 22:30
FYI, this is duplicate of / related to #1533 and #1776

**Comment by carlosVirella** [comment] 2022-12-20 08:50
There's a group of people bothering me everyday at my building they enter to my phone they take out transactions and they keep changing them and saying lots of lies. I've been fighting them a lot while I'm a influential person at securities and investments and crypto. There's specific one girl that talks like a little girl that she is the one planning my everyday destruction. I'm creator of VMWare, Snowflake, Broadcom and many other important securities and seem like there's no peace for me not even on the home side since this people is bothering and harassing me to the point that nobody listens to me. Their bullying is real and i need help confirming myself in front of the S.EC. and others. They destroyed a website called sec report. So if you can talk to someone and make this happen here my number 7187900461 or email CarlosAVirella@gmail.com

**Comment by krOoze** [comment] 2023-01-06 17:22
#1533 only mentions it as an aside and only with special case return code (the meat of the issue seem to be same as #152\#2007).

#1776 seems related, but does not seem to concern with the semaphores and fences.

So, let's keep this one up for now...

**Comment by oddhack** [comment] 2023-01-19 12:04
This should be fixed in the 1.3.239 spec update.

**Closed by oddhack** 2023-01-19 12:04 UTC
Labels: System Integration
