### ISSUE TITLE
Structured relationship management for API items

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/Vulkan-Docs#79] opened 2016-02-24 12:12 UTC
An object and execution model is explained in [the specification chapter "2. Fundamentals"](https://github.com/KhronosGroup/Vulkan-Docs/blob/7e195e846e9b3d7b91c2fe57406a97288261fc5e/doc/specs/vulkan/chapters/fundamentals.txt#L4 "Fundamental description of API entities"). Some [relationships are described for entities](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model "Relationship management") of this application programming interface. It is usual then that such API entities have got a specific construction and destruction order.
* How do you think about to express such software dependencies by a file format which can be automatically processed in a safe way?
* Would you like to [improve the generic handling of outlines](https://en.wikipedia.org/wiki/Model-driven_engineering "Description for model-driven engineering") so that higher level software development services like advanced application validation will be supported?

**Comment by NicolBolas** [comment] 2016-02-24 15:40
Is this not a duplicate of the already closed issue #42? It seems to be asking for the same thing, just in a different way: explicit support in vk.xml to express these relationships, rather than relying on naming conventions.

**Comment by elfring** [comment] 2016-02-24 15:53
I find that this clarification request is not a duplicate issue. - There are different details which I am trying to bring forward here.

* How much do you interpret the specification of additional categories (like "constructor") as relationship management?
* Would you like to express the dependencies between API entities like "instance", "command buffer" and "queue" in a more structured way?

**Comment by TobiasHector** [comment] 2016-02-24 16:05
The xml registry already defines object parent relationships, which defines what order things should be deleted in. So far, this gives us all the information we require in a reasonably simple format. Is there any additional information you specifically want to be expressed, and what are you interested in using it for?

**Comment by elfring** [comment] 2016-02-24 16:16
>The xml registry already defines object parent relationships, which defines what order things should be deleted in.

Which XML schema elements do construct the hierarchical relationship between API instances and subsequent objects?


>Is there any additional information you specifically want to be expressed, and what are you interested in using it for?

Another use case:
Would any more software developers like to check the circumstance when a command buffer is appended to a queue?

**Comment by ratchetfreak** [comment] 2016-02-24 16:25
> Would any more software developers like to check the circumstances when a command buffer is appended to a queue?

They would wait until all queues are idle before shutting down (hopefully). This is possible with calling `vkQueueWaitIdle` or `vkDeviceWaitIdle`. Otherwise they would use the fences to known when the buffer can be reused.

**Comment by TobiasHector** [comment] 2016-02-24 16:26
> Which XML schema elements do construct the hierarchical relationship between API instances and subsequent objects?

The handle definitions for each object have a 'parent' attribute, e.g. https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L205 It's perhaps a bit crude, but it's simple and it works.

**Comment by elfring** [comment] 2016-02-24 16:31
@ratchetfreak: It seems that you would like to share the concern for proper checking of predicates in other use cases.

I am more interested in a clarification for the extraction of useful meta-data from the provided XML (RELAX NG) schema for this issue.

**Comment by elfring** [comment] 2016-02-24 16:39
@TobiasHector:  The handle definitions for each object have a 'parent' attribute, …

Thanks for your hint.


>It's perhaps a bit crude, but it's simple and it works.

* How do you distinguish dispatchable handle types from the non-dispatchable ones according to the Vulkan object model?
* Is the discussed hierarchy consistent in this aspect?

**Comment by ratchetfreak** [comment] 2016-02-24 16:41
You are overestimating my willingness to put up with a graphics API that does too many things behind my back wasting everyone's time (after seeing what opengl has become).

Vulkan is designed from the ground up to put the user code in control of what happens when and if something is called that is not allowed so be it.


> * How do you distinguish dispatchable handle types from the non-dispatchable ones according to the Vulkan object model?

from the type: VK_DEFINE_NON_DISPATCHABLE_HANDLE vs. VK_DEFINE_HANDLE

**Comment by TobiasHector** [comment] 2016-02-25 09:06
> Is the discussed hierarchy consistent in this aspect?

I believe so. If not, it's a bug or something in the spec that I missed when I added those attributes. If you spot anything, please let us know.

**Comment by elfring** [comment] 2016-02-25 13:15
>If you spot anything, please let us know.

Thanks for your offer.

I would appreciate to continue the clarification with the information that you find the parent attribute "a bit crude" for Vulkan handle definitions.
How are the chances to express the provided API hierarchy by the data model in a more direct or logic way?

Does any graphical representation exist for the published object model?

**Comment by TobiasHector** [comment] 2016-02-25 13:36
When I say "it's a bit crude" I mean "it's functional and expresses what we want" and "it's not something you'd find recommended in a Computer Science textbook".

We have no plans to enhance it unless there is a specific need (i.e. some active project depends on additional semantic meaning that's not currently there).

I'm not aware of any graphical representation of the Vulkan object model.

**Comment by elfring** [comment] 2016-02-25 13:45
>"it's not something you'd find recommended in a Computer Science textbook"

I find this feedback particularly interesting.


>… unless there is a specific need (i.e. some active project depends on additional semantic meaning that's not currently there).

How would it become possible to determine safely if an API item is a constructor or destructor for example?


>I'm not aware of any graphical representation of the Vulkan object model.

Would anybody from your organisation like to publish one so that further clarification of various design details might become easier?

**Comment by TobiasHector** [comment] 2016-02-25 14:25
> How would it become possible to determine safely if an API item is a constructor or destructor for example?

We have a semantic rule in Vulkan, so this can be determined easily:
* "vkCreate*" creates a standalone object
* "vkDestroy*" destroys a standalone object
* "vkAllocate*" allocates an object from some larger pool
* "vkFree*" deallocates an object from some larger pool

Where * would be the name of the object being created/destroyed.

> Would anybody from your organisation like to publish one so that further clarification of various design details might become easier?

Probably not at present - we're busy bug fixing and improving other parts of the Vulkan project. It may exist in future, but there are no current plans to do so. If you're interested in learning more about any part of Vulkan, I suggest you pay attention to GDC16, where many sessions will be talking about Vulkan: http://schedule.gdconf.com/search-sessions/Vulkan (A lot of this content ends up online afterwards, if you aren't attending)

**Comment by TobiasHector** [comment] 2016-02-25 14:37
Oh, also I somehow forgot Khronos' own event just outside GDC: https://www.khronos.org/news/events/2016-khronos-sessions-san-francisco
Again - this content should all end up online afterwards.

**Comment by elfring** [comment] 2016-02-25 14:50
>We have a semantic rule in Vulkan, so this can be determined easily:

Thanks for this feedback.


>Where * would be the name of the object being created/destroyed.

I guess that this information is also relevant for [the issue "Advanced categorisation of API functions"](https://github.com/KhronosGroup/Vulkan-Docs/issues/48 "Benefits from taxonomies?"), isn't it?

I would appreciate to reduce the dependency on function name patterns.


>…, where many sessions will be talking about Vulkan: …

I am curious if conference participants (game developers or Khronos visitors) will be also interested in items from this issue tracker.

**Comment by TobiasHector** [comment] 2016-02-25 15:09
> I would appreciate to reduce the dependency on function name patterns.
This correlation will always exist, so you should always be able to rely on it. We might consider doing something more explicit in future - but right now I'm afraid we're not likely to do anything about this.

**Comment by elfring** [comment] 2016-02-25 15:50
>We might consider doing something more explicit in future …

I guess that I would prefer similar fine-tuning for a few more places of the provided data model.

**Comment by TobiasHector** [comment] 2016-02-25 16:00
Given that we're not going to try to change anything now, I'm marking this as enhancement/wontfix and closing. Let us know if you think there's anything left unanswered.

**Closed by TobiasHector** 2016-02-25 16:00 UTC
Labels: enhancement, wontfix

**Comment by elfring** [comment] 2016-02-25 16:17
I am curious if other contributors will trigger any more considerations around fine-tuning for the initial data model.
