### ISSUE TITLE
VkShaderInfoTypeAMD not specified

### ISSUE THREAD

**Issue by TiemoJung** [KhronosGroup/Vulkan-Docs#597] opened 2017-10-23 15:31 UTC
Hi,

it seems that VkShaderInfoTypeAMD is in 1.0.64 not specified.
Its possible enumerations are referenced inside the doc at the appropriate places, but there is no formal definition of VkShaderInfoTypeAMD in the docs.

**Comment by krOoze** [comment] 2017-10-27 19:48
\+ 
`VkShaderResourceUsageAMD` is not documented in the extension appendix.

**Comment by oddhack** [comment] 2017-11-27 11:26
Duplicate of #612, which is WIP inside Khronos.

**Closed by oddhack** 2017-11-27 11:26 UTC
