### ISSUE TITLE
Platform tag not listed as content of registry tags

### ISSUE THREAD

**Issue by RC-1290** [KhronosGroup/Vulkan-Docs#673] opened 2018-03-08 15:39 UTC
The 1.1 version of the Vulkan API Registry mentions the new platform tag in its own chapter, but it isn't yet listed in chapter 4.2. Contents of registry tags.

**Comment by oddhack** [comment] 2018-03-26 09:46
Duplicate of #678

**Closed by oddhack** 2018-03-26 09:46 UTC
Labels: duplicate
