### ISSUE TITLE
Orphaned `vkQueuePresentKHR` paragraphs

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#2008] opened 2022-12-13 16:05 UTC
There seem to be orphaned `vkQueuePresentKHR` paragraphs just below Valid Usage(Implicit) block of `VkSwapchainPresentFenceInfoEXT`. It starts with:

> `vkQueuePresentKHR`, releases the acquisition of the images referenced by `imageIndices`.

Additionally, the comma is kinda odd. It looks like it was also snipped mid sentence by some additions...

**Comment by carlosVirella** [comment] 2022-12-20 08:49
There's a group of people bothering me everyday at my building they enter to my phone they take out transactions and they keep changing them and saying lots of lies. I've been fighting them a lot while I'm a influential person at securities and investments and crypto. There's specific one girl that talks like a little girl that she is the one planning my everyday destruction. I'm creator of VMWare, Snowflake, Broadcom and many other important securities and seem like there's no peace for me not even on the home side since this people is bothering and harassing me to the point that nobody listens to me. Their bullying is real and i need help confirming myself in front of the S.EC. and others. They destroyed a website called sec report. So if you can talk to someone and make this happen here my number 7187900461 or email CarlosAVirella@gmail.com

**Comment by oddhack** [comment] 2022-12-20 09:14
It looks like that was cut & pasted from much higher up in the file. It has been in there for years so good catch. Pinged WSI TSG to try and figure out what was intended.

**Comment by versalinyaa** [comment] 2023-10-11 16:32
cc @versalinyaa

**Comment by oddhack** [comment] 2024-02-16 10:55
This should be fixed in the 1.3.278 spec update.

**Closed by oddhack** 2024-02-16 10:55 UTC
Labels: System Integration, Resolving Inside Khronos
