### ISSUE TITLE
Enums missing from feature section in the registry. 

### ISSUE THREAD

**Issue by mdsitton** [KhronosGroup/Vulkan-Docs#9] opened 2016-02-18 01:38 UTC
Any particular reason why this was omitted. I'm not seeing any other obvious way. Kinda breaks my existing opengl registry parser somewhat (that i was attempting to adapt to use with vulkan).

**Comment by oddhack** [comment] 2016-02-18 02:50
We started off defining enumerants as their own high-level construct, then as we worked out the extension enum assignment scheme - there were a variety proposed - added some tricks to the XML and scripts to handle additions to an enumerated type introduced by extensions. It would be possible to use the same tricks to define the enumerants in a core API feature block, but we haven't chosen to do that. I expect the schema will evolve some more over time as additional information is needed.

**Comment by mdsitton** [comment] 2016-02-18 03:46
Well i'm guessing by "tricks" you mean extends attribute. One option could be to define the enum types as part of a version, then when those types need to be extended in later versions of vulkan they could be handled just like in the extensions.

**Comment by mdsitton** [comment] 2016-05-05 19:31
I'll go ahead and bump this issue as well, any current thoughts/plans related to this?

**Comment by oddhack** [comment] 2016-05-05 20:08
Not at the moment. I expect we'll have to grapple with this when a future Vulkan 1.1 release comes along, but there's no immediate need. Everything in the <enum> blocks is part of 1.0 today.

**Comment by ratchetfreak** [comment] 2016-05-05 20:25
@oddhack put it in a code block with backticks

**Comment by oddhack** [comment] 2016-05-05 20:32
@ratchetfreak it is massive overkill for something in the middle of a sentence. &amp;lt; appears to be the least of the evils but one has to remember to use it.

**Comment by krOoze** [comment] 2016-05-05 20:46
@oddhack Did you just escape that `&lt;` to prove your point and avoid tick block? :) You can also escape it instead of the horrible html macro:  `\<enum\>`.

**Comment by ratchetfreak** [comment] 2016-05-05 21:57
@oddhack  I got a keyboard that lets me create backticks easily so I don't see it as an issue.

However you can hit the `<>` icon in the edit bar in the github when you have something selected for an easy pair of them.

**Comment by oddhack** [comment] 2016-09-17 06:03
Closing this as non-actionable at present. The current XML scheme works well for what it was intended to do and we don't have any significant changes planned, not least because there are a bunch of external consumers (some of them unhappier than others about the particular choices we made).

**Closed by oddhack** 2016-09-17 06:03 UTC
Labels: question, Registry
