### ISSUE TITLE
FragDepth for discarded fragments

### ISSUE THREAD

**Issue by philiptaylor** [KhronosGroup/Vulkan-Docs#47] opened 2016-02-21 20:54 UTC
https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#interfaces-builtin-variables says:

> That is, if the fragment shader enables depth replacing, then it must always write it.

That sounds like it applies even if the fragment shader uses OpKill to discard the fragment. Should it really be required to write to FragDepth in that case?

I guess a similar problem applies if the shader modifies SampleMask so that it doesn't cover any samples - it shouldn't need FragDepth in that case either.

It might be sufficient to simply remove that sentence - the previous sentence already says the depth is undefined on code paths that don't write it, and it seems obvious that a non-discarded fragment/sample mustn't use an undefined depth but a discarded one may.

**Comment by NicolBolas** [comment] 2016-02-22 02:22
Duplicate of #44.

**Comment by oddhack** [comment] 2016-03-05 02:11
Done in the 1.0.5 spec update.

**Closed by oddhack** 2016-03-05 02:11 UTC
Labels: Resolving Inside Khronos, Specification
