### ISSUE TITLE
VK_KHR_swapchain specification missing from XHTML and PDF

### ISSUE THREAD

**Issue by MOARdV** [KhronosGroup/Vulkan-Docs#18] opened 2016-02-18 21:39 UTC
Core specs define function signatures, and describe the structures consumed by the functions.  These extensions don't - they mention the existence of the methods and structures and include examples of use, but don't provide explanation of the parameters and fields.  I can infer and guess at them from the demo files in the SDK and some of the issues in the extension, but it'd be nice to have something more formal that matches the core spec.

**Comment by ianelliottus** [comment] 2016-02-18 22:10
It seems that you are looking at the WSI parts of the appendix (e.g. "E.2 VK_KH_surface").  Please look at the "29. Window System Integration (WSI)" chapter for an introduction to the entire subject area.

**Comment by MOARdV** [comment] 2016-02-18 23:46
For a specific example:

In the copy of the documentation I downloaded on 16 Feb 2016 (vkspec.pdf), a search for the string 'vkCreateSwapchainKHR' turns up no full description.  I see mention of it in section 29.5 a few times, and in the appendix, but nowhere in the documentation do I see the prototype of the function, nor an explanation of the info structure used as a parameter.  I got the documentation from the (Vulkan website)[https://www.khronos.org/registry/vulkan/] by selecting the Core + WSI extensions PDF documentation.

Although inspecting the document again, I see the last page of the chapter read "include::../VK_KHR_swapchain/wsi.txt", so presumably there was an error generating the PDF.  This is still the case as of just now (I checked the link).

**Comment by alonorbach** [comment] 2016-02-18 23:51
Hi @MOARdV. This is a known issue we're looking to rectify ASAP - caused by a syntax typo in the source! Expect a fix to the built specs soon, Meanwhile, you can read from the [source itself](https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0-VK_KHR_swapchain/doc/specs/vulkan/chapters/VK_KHR_swapchain/wsi.txt)

**Comment by MOARdV** [comment] 2016-02-19 03:15
Thanks for the pointer.  I've gotten used to the OpenGL extensions being self-contained in a single file.  I guess the new documentation may impose a learning curve along with the new API. :)

**Comment by oddhack** [comment] 2016-02-26 09:12
This should be fixed in the 1.0.4 updates that were just pushed.

**Closed** 2016-02-26 09:12 UTC
Labels: Resolving Inside Khronos, Specification, WSI
