### ISSUE TITLE
List of typos

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-Docs#352] opened 2016-08-26 14:44 UTC
This is a list of typos in the spec+WSI text. I am not gonna annotate the exact place, so use a text search; some of them occur several times. Without further ado,  here's the grammar nazinesness:

| typo? | correct? |
--------|-----------
| Vulkan 1.0.24 [+ WSI Extensions] - A Specification | _\&mdash;_A Specification |
| flatshading [and word variants]  | flat shading |
| swapchain | swap chain |
| Github | GitHub |
| signalling | signaling [both allowed &mdash; but this variant per style guide] |
| boolean | Boolean |
| ~~a uint32_t~~ | ~~an uint32_t~~ |
| renderpass | render pass |
| [describe] a priori | beforehand |
| accesss | access |
| Javascript | JavaScript |
| pre-initialized | preinitialized |
| mip[X], mip [X] [X=map, mode, tail, level, ?] | [one variant should be chosen] | 
| lod | LOD |
| barrer | barrier |
| a oldSwapchain | an oldSwapchain |
| explict | explicit |
| upate | update |
| rotatation | rotation |
| param | parameter [probably OK &mdash; only in extensions changelogs I think] |
| TODO's | TODOs |
| incuring | incurring |
| platfroms | platforms |
| desireable | desirable |
| pre and current mirror | [?pre? anyway that whole Q&A point seem bit outdated] |
| per-[new line]overlay | per-overlay |
| specificaiton | specification |
| refered | referred |
| determing | determining |
| presention | presentation |
| initializaiton | initialization |
| useable | usable [not wrong, but quite uncommon] |
| conector | connector |
| updataed | updated |
| forseeable | foreseeable |
| synchronizatoin | synchronization |
| semahpore | semaphore |
| opeation | operation |
| vetical | vertical |
| smalled | smalest |
| a 8x[N] | an 8x |
| acccess | access |
| punchthrough | punch-through |
| doublebuffered | double-buffered, double buffered |
| bitplanes | bit planes |
| whitepoint | white point |
| occassion | occasion |
| fuctions | functions |
| assocated | associated |
| controled | controlled |
| an device | a device |
| behaviour | behavior |
| loader-ICD | loader[\&ndash;]ICD |
| loader-layer | loader[\&ndash;]layer |
| rect [offset, size] | rectangle[?] |
| offets | offsets |
| scannout | scanout |
| bitfield | bit field |
| format-colorspace | format[\&ndash;]color space |
| colorspace | color space, colorSpace[parameter description] |
| the the | the |
| ~~tesselation~~ [#327 - closed] | ~~tessellation~~ |
| theglobal | the global |
| an query | a query |
| specifing | specifying |
| a array | an array |
| capabilites | capabilities |
| applicaton | application |

**BTW:**
the styleguide says Asciidoc replaces `--` with **en** dash. That is wrong; it replaces it with **em** dash.

**Comment by oddhack** [comment] 2016-08-29 07:57
Most of these will get fixed. "a uint32_t" is correct if you pronounce "uint32_t" anything like I do. "boolean" is not going to be capitalized any more than "integer". "swapchain" will probably not get changed simply because there are hundreds of instances and the term is very deeply wired into the WSI extension language. I'm sure there will be a healthy argument about "mipX" and nobody will entirely like the result. Personally I like "mipmap" vs. "mipmap level/layer/tail/size" but we'll see what the rest of the WG thinks.

**Comment by krOoze** [comment] 2016-08-29 12:17
I pronounce it "you-int" as in "**u**nsigned" (actually this somehow conveniently exists: https://www.youtube.com/watch?v=smvwbF-D348 :smile: ). 

I wonder if there were Mr. Integ inventing integers... :smirk:
It is just lower-cased in some languages to denote primitive type (it isn't used in that context in the spec, which has its own type and besides use C99). 

Yeah, "swapchain" is hard to change because it became part of the API. Well, languages change... it will get correct sometime in the future :sweat_smile:.

Yeah I added "mip level" and "miplevel" and such just because it seemed it might specifically use consistency (for text search purposes). There are other similar stuff ( "sub" vs "sub-", "pre", "non", "multi", etc. consistency) I ommited completely.

**Comment by philiptaylor** [comment] 2016-08-30 12:40
> I pronounce it "you-int"

That's the only way I've ever heard it pronounced. And that means it should be "a you-int", not "an you-int", since "you" is not a vowel sound, so I think the spec is currently correct. (Same as e.g. "a uniform", though unlike e.g. "an uninformed".)

**Comment by oddhack** [comment] 2016-08-30 12:57
+1 @philiptaylor . Is there a "tongue-tied" emoji?

**Comment by krOoze** [comment] 2016-08-30 13:49
oh, ok. I though you meant "wint" pronunciation. I just discovered I mentally prnounce it with an accent (with silent "y") :tongue: :curly_loop: .

**Comment by philiptaylor** [comment] 2016-08-30 19:01
Ah, like "an oo-int"? I think that's a fairly unusual sound at the start of a word in English pronunciation - I suppose there's "ooze" and some adopted foreign ones like "an Uber" and "an Uzi", but I can't think of many others.

To avoid ambiguity caused by accents, perhaps the style guide needs to declare that all readers must adopt the Queen's English. I'm not sure how many recordings there are of the Queen reading C source code, but maybe she would provide some samples if asked nicely.

**Comment by krOoze** [comment] 2016-08-30 20:33
Yeah, like "Uzi" (short). It's not English at all; neither am I. But I could pass it for what Princess Charlotte might pronounce, if that's enough for you. :smile:

Anyway, that's one crossed off the board.
There are some related (text breaking) issues in #331 list too...

**Comment by oddhack** [comment] 2016-09-06 14:26
This should be fixed in the 1.0.26 spec update, except for the "mip(layer/map/level/etc)" thing which is still being sorted out. Closing to get this off the table, the mip issue is being tracked internally and as soon as people have time to spend on spelling some convention will be adopted and used.

**Closed by oddhack** 2016-09-06 14:26 UTC
Labels: Markup/Editing, Resolving Inside Khronos

**Comment by krOoze** [comment] 2016-09-07 01:53
@oddhack There are some more omissions:

- Styleguide still missleads, that `--` translates to e**n** dash (should be e**m** dash).
- Title still uses hyphen instead of em dash.
- Plenty of places should use en dash, but I guess there's no convenient way to do this in Asciidoc (and you don't want direct Unicode in sources, I suppose)
- Still 2 instances of "flatshading".
- 4 instances of "swap chain" (if "swapchain" preferred now).
- "boolean". (BTW even SPIR-V spec properly uses "Boolean")
- 4 instances of "renderpass"
- "a oldSwapchain", "rotatation", "param", "acccess"
