### ISSUE TITLE
`OpImageFetch` isn't used with a sampler

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-Docs#1749] opened 2022-01-25 16:34 UTC
The section "Instruction/Sampler/Image View Validation" states, at the end:

> `OpImageFetch`, `OpImageSparseFetch`, `OpImage*Gather`, and `OpImageSparse*Gather` **must** not be used with a sampler that enables sampler Y′CBCR conversion.

I think this may be a mistake, because `OpImageFetch` and `OpImageSparseFetch` are both instructions taking an `OpTypeImage`, and not an `OpTypeSampledImage`. No sampler is therefore involved in these instructions. Is it possible that this line in the spec refers not just to samplers using an YCbCr conversion, but also image views using one?

**Comment by sfricke-samsung** [comment] 2022-01-31 16:23
I think the issue is it should say

```patch
- used with a sampler
+ used with a sampler or image view
```

and I raised a potential fix (as well as proper VU statements) for this internally

**Comment by oddhack** [comment] 2022-02-18 10:20
This should be fixed in the 1.3.206 spec update.

**Closed by oddhack** 2022-02-18 10:20 UTC
Labels: Resolving Inside Khronos
