### ISSUE TITLE
VKImageLayout values

### ISSUE THREAD

**Issue by mgoodfel** [KhronosGroup/Vulkan-Docs#159] opened 2016-03-28 11:59 UTC
In VkImageLayout, 

value VK_IMAGE_LAYOUT_PREINITIALIZED is not described.
value VK_IMAGE_LAYOUT_PRESENT_SRC_KHR is not described.

**Comment by oddhack** [comment] 2016-04-01 12:28
In the current 1.0 spec, I see a description for VK_IMAGE_LAYOUT_PREINITIALIZED here: https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkImageLayout

The _KHR token is only defined by one of the WSI extensions, and you can find that in the 1.0-wsi_extensions branch / spec in the registry.

Please close this if you agree the issue is covered.

**Comment by mgoodfel** [comment] 2016-04-01 19:57
I've been using

https://vulkan.lunarg.com/v1/docs/v1.0.5.0/vulkandocs/apispec.html#VkImageLayout

That is still not updated.  Is that generated from the xhtml file?

Michael.

**Comment by oddhack** [comment] 2016-04-01 22:03
LunarG updates it. I don't know how often they do so. But the latest spec will always be found at www.khronos.org/registry/vulkan/ .

**Comment by philiptaylor** [comment] 2016-04-01 22:35
apispec.html is the API Reference Pages document, which is different to the API Specification (despite the filename). The reference pages are known to have a lot of problems at the moment and need a lot of work, so you probably shouldn't use them as a reference - use the API Specification instead.

**Closed** 2016-04-02 01:05 UTC
